# -*- mode: ruby -*-
# vi: set ft=ruby :

require "erb"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"

  config.vm.network :forwarded_port, guest: 5432, host: 5432
  config.vm.network :private_network, ip: "10.0.54.32"

  config.vm.synced_folder ".", "/vagrant", type: :nfs

  directory = File.dirname(__FILE__)

  @bind_ip = "0.0.0.0"
  postgresql_conf = ERB.new(File.read("#{directory}/conf/postgresql.conf.erb", mode: "r"))
  File.write("#{directory}/conf/postgresql.conf", postgresql_conf.result(binding), mode: "w")

  pg_hba_conf = ERB.new(File.read("#{directory}/conf/pg_hba.conf.erb", mode: "r"))
  File.write("#{directory}/conf/pg_hba.conf", pg_hba_conf.result(binding), mode: "w")

  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "postgresql-service"
    vbox.memory = 4096
    vbox.cpus = 4
  end

  config.vm.provision :shell, path: "vagrant_bootstrap.sh", keep_color: true, privileged: false
end
