# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chrisvire/lucid32"
  config.vm.hostname = "vagrant"

  config.vm.network :private_network, ip: "10.0.10.20"

  config.vm.synced_folder ".", "/vagrant", type: :nfs
  config.vm.synced_folder "/Users/kja/dev/smashthestack", "/smashthestack", type: :nfs

  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "ubuntu-lucid32"
    vbox.memory = 1024
    vbox.cpus = 2
  end

  config.vm.provision :shell, path: "vagrant_bootstrap.sh", keep_color: true, privileged: false
end
