# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "kja/netbsd-7-amd64"

  config.vm.network :private_network, ip: "10.0.10.30"

  config.vm.synced_folder ".", "/vagrant", type: :nfs
  config.vm.synced_folder "/Users/kja/dev/metal", "/metal", type: :nfs

  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "netbsd-vanilla"
    vbox.memory = 2048
    vbox.cpus = 2
  end

  config.vm.provision :shell, path: "vagrant_bootstrap.sh", keep_color: true, privileged: false
end
