# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "freebsd/FreeBSD-10.2-RELEASE"

  config.vm.base_mac = "080027FCBD3B"

  config.vm.network :private_network, ip: "10.0.10.20"

  config.vm.synced_folder ".", "/vagrant", type: :nfs
  config.vm.synced_folder "/Users/kja/dev/metal", "/metal", type: :nfs

  config.ssh.shell = 'sh'

  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "freebsd-vanilla"
    vbox.memory = 2048
    vbox.cpus = 2
  end

  config.vm.provision :shell, path: "vagrant_bootstrap.sh", keep_color: true, privileged: false
end
