# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'erb'

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"

  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.network :private_network, ip: '10.0.80.80'
  config.vm.synced_folder '.', '/vagrant', nfs: true

  directory = File.dirname(__FILE__)

  @bind_address = "0.0.0.0"
  @bind_port = 80
  nginx_conf_template = ERB.new(File.read("#{directory}/conf/nginx.conf.erb", mode: 'r'))
  File.write("#{directory}/conf/nginx.conf", nginx_conf_template.result(binding), mode: 'w')

  default_site_template = ERB.new(File.read("#{directory}/conf/sites/default.erb", mode: 'r'))
  File.write("#{directory}/conf/sites/default", default_site_template.result(binding), mode: 'w')

  config.vm.provider :virtualbox do |vbox|
    vbox.name = "nginx-service"
    vbox.memory = 512
    vbox.cpus = 1
  end

  config.vm.provision :shell, path: "vagrant_bootstrap.sh", keep_color: true, privileged: false
end
