# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'erb'

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"
  config.vm.hostname = "nginx-service"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true

  # Use NFS for much better performance
  config.vm.network :private_network, ip: '10.0.80.80'
  config.vm.synced_folder '.', '/vagrant', nfs: true

  directory = File.dirname(__FILE__)

  @bind_address = "0.0.0.0"
  @bind_port = 80
  nginx_conf_template = ERB.new(File.read("#{directory}/conf/nginx.conf.erb", mode: 'r'))
  File.write("#{directory}/conf/nginx.conf", nginx_conf_template.result(binding), mode: 'w')

  default_site_template = ERB.new(File.read("#{directory}/conf/sites/default.erb", mode: 'r'))
  File.write("#{directory}/conf/sites/default", default_site_template.result(binding), mode: 'w')

  config.vm.provider :virtualbox do |vbox|
    vbox.name = "nginx-service"
    vbox.memory = 1024
  end

  config.vm.provision :shell, path: "vagrant_bootstrap.sh", keep_color: true, privileged: false
end
