# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "vagrant"

  config.vm.network :private_network, ip: "10.0.10.10"

  config.vm.synced_folder ".", "/vagrant", type: :nfs

  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "ubuntu-vanilla"
    vbox.memory = 2048
    vbox.cpus = 2
  end

  config.vm.provision :shell, path: "vagrant_bootstrap.sh", keep_color: true, privileged: false
end
