# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'erb'

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "vagrant"

  config.vm.network :forwarded_port, guest: 6379, host: 6379
  config.vm.network :private_network, ip: "10.0.63.79"

  config.vm.synced_folder ".", "/vagrant", type: :nfs

  directory = File.dirname(__FILE__)

  @redis_bind_ip = "0.0.0.0"
  redis_conf = ERB.new(File.read("#{directory}/conf/redis.conf.erb", mode: 'r'))
  File.write("#{directory}/conf/redis.conf", redis_conf.result(binding), mode: 'w')

  config.vm.provider "virtualbox" do |vbox|
    vbox.name = 'redis-service'
    vbox.cpus = 1
    vbox.memory = 512
  end

  config.vm.provision :shell, path: "vagrant_bootstrap.sh", keep_color: true, privileged: false
end
